baseURL = "https://ethan-putnam.com/"
languageCode = "en-us"
title = "Ethan Putnam"
theme = "minimal"

[params]
author = "Ethan Putnam"
description = "Personal website of Ethan Putnam"
tagline = "PhD Student in Cellular Molecular and Biomedical Sciences"
affiliation = "University of Vermont"
email = "esputnam@uvm.edu"
profileImage = "/images/webphoto.jpeg"

bio = """
I am a <strong>2nd year PhD student</strong> in the CMB program at the University of Vermont advised by <a href="https://umicrobiomelab.org/" target="_blank">Dani Brasino</a>. My research focuses on developing an optimized gut organ-on-chip model system to investigate host-microbe interactions in cancer.

Previously, I worked for the <a href="https://cancercenter.gwu.edu/profile/javad-nazarian" target="_blank">Nazarian Lab</a> at Children's National on model development for transformed NF1 gliomas and was a member of the <a href="https://www.uvm.edu/cas/psychology/profile/mark-e-bouton" target="_blank">Bouton Lab</a> at UVM during my undergrad.
"""

research = [
    "Research Interest 1",
    "Research Interest 2",
    "Research Interest 3",
    "Research Interest 4"
]

address = """
Cellular, Molecular and Biomedical Sciences
University of Vermont
Burlington, VT 05405
"""

[[params.leadership]]
organization = "University of Vermont Outing Club"
role = "Outing Club Leader"
date = "Feb. 2018-May 2021"
description = "Completed a competitive leadership development course and led wilderness excursions for UVM students in Vermont, New Hampshire, and New York."


[[params.social]]
name = "GitHub"
url = "https://github.com/nucloid1"

[[params.social]]
name = "Google Scholar"
url = "https://scholar.google.com/citations?user=nr45zt8AAAAJ&hl=en&oi=ao"

[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/ethan-putnam-67b217176/"

[menu]
[[menu.main]]
name = "Blog"
url = "https://substack.com/@ethanputnam"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[markup]
[markup.goldmark.renderer]
unsafe = true
